color: null
fieldLayouts:
  8e1fdb74-e71a-4e0a-a925-28b19fe57019:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-02-18T19:13:53+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: bd99412b-5ef5-40bc-9754-e1f3c0f43b06
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-19T19:44:16+00:00'
            elementCondition: null
            fieldUid: 8f9a6657-d317-4437-901b-c6b288884f78 # Sermon Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 87f3e3f3-04f0-4727-9ef6-5404a5989e0c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-18T19:56:42+00:00'
            elementCondition: null
            fieldUid: 3e96336e-e803-42d5-999f-cb19aa129537 # Sermon Date	
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e01f7339-db46-4086-bb9f-3f65960f8773
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-18T19:56:42+00:00'
            elementCondition: null
            fieldUid: 0cfb3f2f-91a0-46dc-8a1f-a3d99e594c4a # Speaker Name	
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 35b454af-a3a6-4fc8-9edf-4c1e9079df0f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-18T19:56:42+00:00'
            elementCondition: null
            fieldUid: a5bab881-3249-4db3-93ee-4e15ce9915e2 # Sermon Description	
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 641cecfd-3654-477d-9e12-153473fa16b5
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-18T19:56:42+00:00'
            elementCondition: null
            fieldUid: 2ccb4a24-9764-4f39-ade9-57dc2b7526db # Sermon Audio File	
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e0224f6d-3fa2-430d-baf6-dd73d6a1e67a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 40485204-a6e1-42dd-840d-220d320ec12f
        userCondition: null
handle: audioSermonEntry
hasTitleField: true
icon: null
name: 'Audio Sermon Entry'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{title}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
