color: null
fieldLayouts:
  dcc7037b-d7f4-49f8-9171-e115a50b1d1d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-03-04T20:45:29+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: df9d272c-b741-4b8f-a667-d4f7f4b65210
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-04T20:52:04+00:00'
            elementCondition: null
            fieldUid: e61d63c3-2614-4498-8d3e-ba411de9813a # Attendee Name
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1a8ed55e-59fe-40fb-9d4c-36aed574b247
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-04T20:52:04+00:00'
            elementCondition: null
            fieldUid: 9cdee50b-57cc-4c34-824d-3b090381e3ba # Attendee Email
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 823287db-f410-4138-9dd8-a032dd8b792b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-04T20:52:04+00:00'
            elementCondition: null
            fieldUid: 66fe051e-37cc-4947-9784-d0a741883d91 # Related Sermon
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ca67ab72-f4fa-44bc-b809-0a55e65ae90d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: b9c016b5-2d2f-4a01-822e-8752b5ee6917
        userCondition: null
handle: sermonSignUp
hasTitleField: true
icon: null
name: 'Sermon Sign-up'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{attendeeName} - {relatedSermon.one().title}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
