baseUrl: $PRIMARY_SITE_URL
enabled: true
handle: en
hasUrls: true
language: en-US
name: 'bethesda ministry (ENG)'
primary: true
siteGroup: 3db45ca2-4cff-46f3-9796-4678f3533148 # bethesda ministry
sortOrder: 1
