altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  5cda8832-f268-4991-8f4a-03fb4b24c18d:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-08-04T15:55:45+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: c3b81867-5411-4a7e-ae17-322353e35881
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0e4c62c3-6322-4a5b-a400-c03297fda273
        userCondition: null
fs: localAssets
handle: artistsImages
name: 'Artists Images'
sortOrder: 3
subpath: artists-images
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
