altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  30254636-084e-46c7-8d69-2175aa7f69c5:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-08-04T17:37:52+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 6d9b7898-bc6d-4316-a4d3-1770d7af5b44
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8c7b785a-f986-410f-affb-a0f0954a0c14
        userCondition: null
fs: localAssets
handle: authorImages
name: 'Author Images'
sortOrder: 10
subpath: author-images
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
