altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  b86a40f8-7431-4dce-a2f9-3ffaa111dad8:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-08-04T15:57:11+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: f7d98c4c-1371-42e1-9421-f057dbad5f73
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f0a10d23-37ac-44cb-9413-07332657eb4c
        userCondition: null
fs: localAssets
handle: heroImages
name: 'Hero Images'
sortOrder: 6
subpath: hero-images
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
