altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  e5e12b57-d5e4-4341-8c32-54a0ed9ed21a:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-08-05T14:52:14+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: e34643cd-85fe-4c66-9e1f-3bfb154effc0
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f64b2b6c-345b-4a1f-b1e3-d0b5b6ef693c
        userCondition: null
fs: localAssets
handle: historyImage
name: 'History Image'
sortOrder: 11
subpath: history-images
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
