altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  55e06223-0f6a-45d2-90e2-4f32f7b13abd:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-08-04T15:57:41+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: f6517e50-3773-4fa1-90e0-a0f414a9f574
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 75d61205-6faf-4a90-af1e-0c60748826ef
        userCondition: null
fs: localAssets
handle: memberImages
name: 'Member Images'
sortOrder: 7
subpath: member-images
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
