altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  9af791f4-5558-4d43-b79d-f168ba3048dd:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-08-04T15:57:54+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 2bb2516c-5c8e-4a9d-b02b-e3b81755ee38
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 67d69b01-0011-4afa-b436-05fda73c822d
        userCondition: null
fs: localAssets
handle: sermonImages
name: 'Sermon Images'
sortOrder: 8
subpath: sermon-images
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
