altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  9755578f-b34c-4c61-a389-c63fd316168c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-02-18T21:03:32+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 96acebf9-2c61-4aeb-a0f9-66d53d10cb0b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: cd0024b8-f16a-405a-8e5c-54c2fd15ce06
        userCondition: null
fs: uploads
handle: uploads
name: Uploads
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
