columnSuffix: null
handle: eventDate
instructions: "Stores event date/time.\r\n"
name: "Event Date\t"
searchable: false
settings:
  max: null
  min: null
  minuteIncrement: 15
  showDate: true
  showTime: true
  showTimeZone: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Date
