columnSuffix: null
handle: isfeatured
instructions: null
name: isFeatured
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
