columnSuffix: null
handle: itemLimit
instructions: null
name: 'Item Limit'
searchable: false
settings:
  decimals: 0
  defaultValue: null
  max: 9
  min: 0
  prefix: null
  previewCurrency: null
  previewFormat: decimal
  size: null
  step: 3
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
