columnSuffix: null
handle: membershipBenefits
instructions: null
name: 'Membership Benefits'
searchable: false
settings:
  addRowLabel: 'Add a row'
  columns:
    __assoc__:
      -
        - col1
        -
          __assoc__:
            -
              - heading
              - 'Benefit Text'
            -
              - handle
              - benefitText
            -
              - width
              - ''
            -
              - type
              - singleline
      -
        - col2
        -
          __assoc__:
            -
              - heading
              - 'Show Benefit'
            -
              - handle
              - showBenefit
            -
              - width
              - ''
            -
              - type
              - lightswitch
  defaults:
    -
      __assoc__:
        -
          - col1
          - ''
        -
          - col2
          - ''
  maxRows: null
  minRows: null
  staticRows: false
translationKeyFormat: null
translationMethod: site
type: craft\fields\Table
