columnSuffix: null
handle: prayerMessage
instructions: "The actual prayer request message.\r\n"
name: "Prayer Request\t"
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
