columnSuffix: null
handle: requesterName
instructions: "The name of the person submitting the request.\r\n"
name: Name
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
