columnSuffix: null
handle: sermonDate
instructions: 'Stores when the sermon will be delivered.'
name: "Sermon Date\t"
searchable: false
settings:
  max: null
  min: null
  minuteIncrement: 15
  showDate: true
  showTime: true
  showTimeZone: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Date
