columnSuffix: null
handle: showBenefit
instructions: null
name: 'Show Benefit'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
