columnSuffix: null
handle: showArticlesSection
instructions: null
name: 'Show Articles Section'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
