columnSuffix: null
handle: showEventsSection
instructions: null
name: 'Show Events Section'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
