columnSuffix: null
handle: speakerName
instructions: null
name: "Speaker Name\t"
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 4
  multiline: false
  placeholder: 'Name of the pastor/speaker.'
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
