columnSuffix: null
handle: subscriberlanguage
instructions: null
name: Language
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - English
        -
          - value
          - english
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Nederlands
        -
          - value
          - nederlands
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Francais
        -
          - value
          - francais
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: site
type: craft\fields\Dropdown
