defaultPlacement: end
enableVersioning: false
entryTypes:
  -
    uid: 4b7ea142-0c5d-41f9-a62d-3c6a5fdd8e3c # Contact Message
handle: contactMessages
maxAuthors: 1
name: 'Contact Messages'
propagationMethod: all
siteSettings:
  5607335d-3b23-47a6-acee-41d4ffb0462c: # bethesda ministry
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
