defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 2b7e5251-bbfa-466e-8130-243065c9294e # Donate Page
handle: donatePage
maxAuthors: 1
name: 'Donate Page'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  3b691aff-4e3c-4d71-8837-7c4c8d0328b1: # bethesda ministry (NL)
    enabledByDefault: true
    hasUrls: true
    template: donate/index.twig
    uriFormat: donate
  2990f109-c546-4a97-a92f-2c3e7cb2c263: # bethesda ministry (FR)
    enabledByDefault: true
    hasUrls: true
    template: donate/index.twig
    uriFormat: donate
  5607335d-3b23-47a6-acee-41d4ffb0462c: # bethesda ministry (ENG)
    enabledByDefault: true
    hasUrls: true
    template: donate/index.twig
    uriFormat: donate
type: single
