defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 789f6b17-9de5-4839-a76d-94cc5d206f76 # Event Sign-up
handle: eventSignUps
maxAuthors: 1
name: 'Event Sign-ups'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - refresh
        - '1'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  5607335d-3b23-47a6-acee-41d4ffb0462c: # bethesda ministry (ENG)
    enabledByDefault: true
    hasUrls: true
    template: event-sign-ups/_entry.twig
    uriFormat: 'event-sign-ups/{slug}'
type: channel
