defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 5913f12c-3af8-4eb3-ba8f-03469428c3af # Event Entry
handle: events
maxAuthors: 1
name: Events
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  5607335d-3b23-47a6-acee-41d4ffb0462c: # bethesda ministry
    enabledByDefault: true
    hasUrls: true
    template: events/_entry.twig
    uriFormat: 'events/{slug}'
type: channel
