defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 89226c1f-2d7f-4d1b-a5d1-0f4ed31fc49b # Membership Page
handle: membershipPage
maxAuthors: 1
name: 'Membership Page'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  3b691aff-4e3c-4d71-8837-7c4c8d0328b1: # bethesda ministry (NL)
    enabledByDefault: true
    hasUrls: true
    template: membership-page/_entry.twig
    uriFormat: membership-page
  2990f109-c546-4a97-a92f-2c3e7cb2c263: # bethesda ministry (FR)
    enabledByDefault: true
    hasUrls: true
    template: membership-page/_entry.twig
    uriFormat: membership-page
  5607335d-3b23-47a6-acee-41d4ffb0462c: # bethesda ministry (ENG)
    enabledByDefault: true
    hasUrls: true
    template: membership-page/_entry.twig
    uriFormat: membership-page
type: single
