tabs:
  -
    elementCondition: null
    elements:
      -
        autocapitalize: true
        autocomplete: false
        autocorrect: true
        class: null
        dateAdded: '2025-03-22T19:28:25+01:00'
        disabled: false
        elementCondition: null
        id: null
        includeInCards: false
        inputType: null
        instructions: null
        label: null
        max: null
        min: null
        name: null
        orientation: null
        placeholder: null
        providesThumbs: false
        readonly: false
        requirable: false
        size: null
        step: null
        tip: null
        title: null
        type: craft\fieldlayoutelements\addresses\LabelField
        uid: 99c258e9-e1bb-470f-b999-7446236b6469
        userCondition: null
        warning: null
        width: 100
      -
        attribute: countryCode
        dateAdded: '2025-03-22T19:28:25+01:00'
        elementCondition: null
        id: null
        includeInCards: false
        instructions: null
        label: null
        orientation: null
        providesThumbs: false
        requirable: false
        tip: null
        type: craft\fieldlayoutelements\addresses\CountryCodeField
        uid: 17196958-0253-43ae-a5f6-9c6b4f7447ec
        userCondition: null
        warning: null
        width: 100
      -
        dateAdded: '2025-03-22T19:28:25+01:00'
        elementCondition: null
        includeInCards: true
        instructions: null
        label: null
        providesThumbs: false
        required: false
        tip: null
        type: craft\fieldlayoutelements\addresses\AddressField
        uid: fbd811d9-1afd-4029-b758-20fa097a4e21
        userCondition: null
        warning: null
    name: Content
    uid: 9ce78830-49c7-471c-aba7-1afb19c5cc72
    userCondition: null
