name: Prod Readiness Check
on: [push, workflow_dispatch]

jobs:
  prod-check:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: craft_ci
        ports: ["3306:3306"]
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -proot"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=20

    steps:
      - uses: actions/checkout@v4

      - name: Repo sanity
        run: |
          ls -la
          test -d web || (echo "Missing web/ docroot" && exit 1)
          test -d config/project || (echo "Missing config/project" && exit 1)
          test -f composer.json || (echo "Missing composer.json" && exit 1)
          test -f composer.lock || (echo "composer.lock missing – commit it" && exit 1)
          test ! -f .env || (echo ".env SHOULD NOT be committed" && exit 1)

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, gd, imagick, pdo_mysql, curl, openssl, dom, fileinfo, exif, zip
          ini-values: memory_limit=512M
          tools: composer:v2

      - name: Install PHP deps (prod-like)
        run: composer install --no-dev --prefer-dist --no-interaction

      - name: Wait for MySQL & create DB
        run: |
          for i in {1..30}; do
            mysql -h 127.0.0.1 -uroot -proot -e "SELECT 1" && break
            echo "MySQL not ready, retry $i/30"; sleep 2
          done
          mysql -h 127.0.0.1 -uroot -proot -e "CREATE DATABASE IF NOT EXISTS craft_ci CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"

      - name: Create CI .env
        run: |
          cat > .env <<'EOF'
          CRAFT_ENVIRONMENT=production
          DEV_MODE=false
          ALLOW_ADMIN_CHANGES=true
          SECURITY_KEY=ci-test-key

          PRIMARY_SITE_URL=http://localhost
          SITE_URL=http://localhost

          DB_DRIVER=mysql
          DB_SERVER=127.0.0.1
          DB_PORT=3306
          DB_DATABASE=craft_ci
          DB_USER=root
          DB_PASSWORD=root

          EMAIL_DRIVER=sendmail
          STRIPE_MODE=test
          STRIPE_SECRET_KEY=sk_test_dummy
          STRIPE_PUBLISHABLE_KEY=pk_test_dummy
          STRIPE_WEBHOOK_SECRET=whsec_dummy
          EOF

      - name: Craft CLI available
        run: php craft --help

      - name: Apply project config & run migrations
        run: |
          php craft project-config/apply --no-backup -n
          php craft migrate/all -n
          php craft clear-caches/all -n

      - name: Red flags
        run: |
          if git ls-files | grep -q '^vendor/'; then echo "ERROR: vendor/ is committed"; exit 1; fi
          if git ls-files | grep -q '^.env$'; then echo "ERROR: .env is committed"; exit 1; fi

      - name: Success
        run: echo "✅ Deployment-ready."
